dataset: final_dataset-test_0.05/test/unseen_map
which_test: unseen_map
save_dir: video
new_dataset_name: dataset-with-vel-map
num_unseen_map: 47
test_percentage: 0.05
run_mode: hil
sim_mode: eval
data_base: 'datasets'
data_aug: 0
map_config: 'rnd_obstacle_v2'
strategy_name: 'success_1'
trained_model: ''
ep: 0
save_img: True
control_type: 'continuous'
traj_dir: ''
dp_mode: 'demo'