START: [0.05, 0.82]
START_ORIENTATION: 90
GOAL: [0.7, 0.6] # these are factors multiplied to window width and height
OBSTACLES:
- COUNT: 3
  POSITIONS: [[0.15, 0.62], [0.49, 0.27], [0.85, 0.46]] #these are factors multiplied to window width and height
  SIZES: [[50, 470], [850, 50], [50, 280]] # in pixels
