NAME: "one_obstacle"
START: [0.2, 0.5]
START_ORIENTATION: 90
GOAL: [0.8, 0.5] # these are factors multiplied to window width and height
OBSTACLES:
- COUNT: 1
  POSITIONS: [[0.5, 0.5]] #these are factors multiplied to window width and height
  SIZES: [[70, 70]] # in pixels
